# Generated by Django 5.1.6 on 2025-02-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Naziv kompanije')),
                ('tax_number', models.CharField(max_length=9, unique=True, verbose_name='PIB')),
                ('registration_number', models.CharField(max_length=8, unique=True, verbose_name='Matični broj')),
                ('address', models.CharField(max_length=255, verbose_name='Adresa')),
                ('city', models.CharField(choices=[('Aleksinac', 'Aleksinac'), ('Aranđelovac', 'Aranđelovac'), ('Bačka Palanka', 'Bačka Palanka'), ('Bačka Topola', 'Bačka Topola'), ('Bajina Bašta', 'Bajina Bašta'), ('Belgrade', 'Belgrade'), ('Bečej', 'Bečej'), ('Bor', 'Bor'), ('Gornji Milanovac', 'Gornji Milanovac'), ('Inđija', 'Inđija'), ('Jagodina', 'Jagodina'), ('Kikinda', 'Kikinda'), ('Kladovo', 'Kladovo'), ('Knjaževac', 'Knjaževac'), ('Kragujevac', 'Kragujevac'), ('Kraljevo', 'Kraljevo'), ('Kruševac', 'Kruševac'), ('Kučevo', 'Kučevo'), ('Leskovac', 'Leskovac'), ('Loznica', 'Loznica'), ('Negotin', 'Negotin'), ('Niš', 'Niš'), ('Nova Varoš', 'Nova Varoš'), ('Novi Pazar', 'Novi Pazar'), ('Novi Sad', 'Novi Sad'), ('Pančevo', 'Pančevo'), ('Paraćin', 'Paraćin'), ('Pirot', 'Pirot'), ('Požarevac', 'Požarevac'), ('Prijepolje', 'Prijepolje'), ('Prokuplje', 'Prokuplje'), ('Ruma', 'Ruma'), ('Smederevo', 'Smederevo'), ('Sombor', 'Sombor'), ('Sremska Mitrovica', 'Sremska Mitrovica'), ('Subotica', 'Subotica'), ('Svilajnac', 'Svilajnac'), ('Šabac', 'Šabac'), ('Užice', 'Užice'), ('Valjevo', 'Valjevo'), ('Velika Plana', 'Velika Plana'), ('Vranje', 'Vranje'), ('Vrnjačka Banja', 'Vrnjačka Banja'), ('Vršac', 'Vršac'), ('Zaječar', 'Zaječar'), ('Zrenjanin', 'Zrenjanin'), ('Čačak', 'Čačak')], max_length=100, verbose_name='Grad')),
                ('postal_code', models.CharField(max_length=5, verbose_name='Poštanski broj')),
                ('industry', models.CharField(choices=[('agriculture', 'Poljoprivreda, šumarstvo i ribarstvo'), ('mining', 'Rudarstvo'), ('manufacturing', 'Prerađivačka industrija'), ('energy', 'Snabdevanje električnom energijom, gasom i parom'), ('water_supply', 'Snabdevanje vodom i upravljanje otpadnim vodama'), ('construction', 'Građevinarstvo'), ('geodetic', 'Geodetske usluge'), ('trade', 'Trgovina na veliko i malo'), ('transportation', 'Saobraćaj i skladištenje'), ('tourism', 'Turizam i turističke usluge'), ('hospitality', 'Usluge smeštaja i ishrane'), ('information', 'Informisanje i komunikacije'), ('it_services', 'IT usluge i razvoj softvera'), ('finance', 'Finansijske delatnosti i osiguranje'), ('real_estate', 'Poslovanje nekretninama'), ('professional', 'Stručne, naučne i tehničke delatnosti'), ('administrative', 'Administrativne i pomoćne uslužne delatnosti'), ('public_admin', 'Državna uprava i odbrana'), ('education', 'Obrazovanje'), ('healthcare', 'Zdravstvena i socijalna zaštita'), ('arts', 'Umetnost, zabava i rekreacija'), ('other_services', 'Ostale uslužne delatnosti'), ('legal_services', 'Pravne usluge'), ('consulting', 'Konsalting usluge'), ('marketing', 'Marketing i oglašavanje'), ('households', 'Delatnost domaćinstva kao poslodavca'), ('extraterritorial', 'Delatnost eksteritorijalnih organizacija i tela')], max_length=50, verbose_name='Industrija')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Kontakt osoba')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Kontakt telefon')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Kontakt email')),
                ('notes', models.TextField(blank=True, verbose_name='Napomene')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivno')),
            ],
            options={
                'verbose_name': 'Kompanija',
                'verbose_name_plural': 'Kompanije',
                'ordering': ['name'],
            },
        ),
    ]
