# Generated by Django 5.1.6 on 2025-02-25 16:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kompanija', 'verbose_name_plural': 'Kompanije'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tax_number',
        ),
        migrations.AddField(
            model_name='company',
            name='annual_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Godišnji prihod'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pozicija kontakt osobe'),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default='Srbija', max_length=100, verbose_name='Država'),
        ),
        migrations.AddField(
            model_name='company',
            name='mb',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Matični broj mora sadržati tačno 8 cifara')], verbose_name='Matični broj'),
        ),
        migrations.AddField(
            model_name='company',
            name='number_of_employees',
            field=models.IntegerField(blank=True, null=True, verbose_name='Broj zaposlenih'),
        ),
        migrations.AddField(
            model_name='company',
            name='pib',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'PIB mora sadržati tačno 9 cifara')], verbose_name='PIB'),
        ),
        migrations.AddField(
            model_name='company',
            name='secondary_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email druge kontakt osobe'),
        ),
        migrations.AddField(
            model_name='company',
            name='secondary_contact_person',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Druga kontakt osoba'),
        ),
        migrations.AddField(
            model_name='company',
            name='secondary_contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon druge kontakt osobe'),
        ),
        migrations.AddField(
            model_name='company',
            name='secondary_contact_position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pozicija druge kontakt osobe'),
        ),
        migrations.AddField(
            model_name='company',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ulica'),
        ),
        migrations.AddField(
            model_name='company',
            name='street_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Broj'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, choices=[('Aleksinac', 'Aleksinac'), ('Aranđelovac', 'Aranđelovac'), ('Bačka Palanka', 'Bačka Palanka'), ('Bačka Topola', 'Bačka Topola'), ('Bajina Bašta', 'Bajina Bašta'), ('Belgrade', 'Belgrade'), ('Bečej', 'Bečej'), ('Bor', 'Bor'), ('Gornji Milanovac', 'Gornji Milanovac'), ('Inđija', 'Inđija'), ('Jagodina', 'Jagodina'), ('Kikinda', 'Kikinda'), ('Kladovo', 'Kladovo'), ('Knjaževac', 'Knjaževac'), ('Kragujevac', 'Kragujevac'), ('Kraljevo', 'Kraljevo'), ('Kruševac', 'Kruševac'), ('Kučevo', 'Kučevo'), ('Leskovac', 'Leskovac'), ('Loznica', 'Loznica'), ('Negotin', 'Negotin'), ('Niš', 'Niš'), ('Nova Varoš', 'Nova Varoš'), ('Novi Pazar', 'Novi Pazar'), ('Novi Sad', 'Novi Sad'), ('Pančevo', 'Pančevo'), ('Paraćin', 'Paraćin'), ('Pirot', 'Pirot'), ('Požarevac', 'Požarevac'), ('Prijepolje', 'Prijepolje'), ('Prokuplje', 'Prokuplje'), ('Ruma', 'Ruma'), ('Smederevo', 'Smederevo'), ('Sombor', 'Sombor'), ('Sremska Mitrovica', 'Sremska Mitrovica'), ('Subotica', 'Subotica'), ('Svilajnac', 'Svilajnac'), ('Šabac', 'Šabac'), ('Užice', 'Užice'), ('Valjevo', 'Valjevo'), ('Velika Plana', 'Velika Plana'), ('Vranje', 'Vranje'), ('Vrnjačka Banja', 'Vrnjačka Banja'), ('Vršac', 'Vršac'), ('Zaječar', 'Zaječar'), ('Zrenjanin', 'Zrenjanin'), ('Čačak', 'Čačak')], help_text='Izaberite grad', max_length=50, null=True, verbose_name='Grad'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email kontakt osobe'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kontakt osoba'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon kontakt osobe'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, choices=[('agriculture', 'Poljoprivreda, šumarstvo i ribarstvo'), ('mining', 'Rudarstvo'), ('manufacturing', 'Prerađivačka industrija'), ('energy', 'Snabdevanje električnom energijom, gasom i parom'), ('water_supply', 'Snabdevanje vodom i upravljanje otpadnim vodama'), ('construction', 'Građevinarstvo'), ('geodetic', 'Geodetske usluge'), ('trade', 'Trgovina na veliko i malo'), ('transportation', 'Saobraćaj i skladištenje'), ('tourism', 'Turizam i turističke usluge'), ('hospitality', 'Usluge smeštaja i ishrane'), ('information', 'Informisanje i komunikacije'), ('it_services', 'IT usluge i razvoj softvera'), ('finance', 'Finansijske delatnosti i osiguranje'), ('real_estate', 'Poslovanje nekretninama'), ('professional', 'Stručne, naučne i tehničke delatnosti'), ('administrative', 'Administrativne i pomoćne uslužne delatnosti'), ('public_admin', 'Državna uprava i odbrana'), ('education', 'Obrazovanje'), ('healthcare', 'Zdravstvena i socijalna zaštita'), ('arts', 'Umetnost, zabava i rekreacija'), ('other_services', 'Ostale uslužne delatnosti'), ('legal_services', 'Pravne usluge'), ('consulting', 'Konsalting usluge'), ('marketing', 'Marketing i oglašavanje'), ('households', 'Delatnost domaćinstva kao poslodavca'), ('extraterritorial', 'Delatnost eksteritorijalnih organizacija i tela')], help_text='Izaberite industriju', max_length=50, null=True, verbose_name='Industrija'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktivna'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Naziv kompanije'),
        ),
        migrations.AlterField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Napomene'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Poštanski broj'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Web sajt'),
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_no', models.CharField(blank=True, max_length=10, null=True, verbose_name='Broj sertifikata')),
                ('init_reg_date', models.DateField(blank=True, null=True, verbose_name='Datum inicijalne registracije')),
                ('standard', models.CharField(blank=True, choices=[('ISO 9001:2015', 'ISO 9001:2015 - Sistem menadžmenta kvalitetom'), ('ISO 14001:2015', 'ISO 14001:2015 - Sistem upravljanja zaštitom životne sredine'), ('ISO 45001:2018', 'ISO 45001:2018 - Sistem menadžmenta bezbednošću i zdravljem na radu'), ('ISO 27001:2022', 'ISO 27001:2022 - Sistem menadžmenta bezbednošću informacija'), ('ISO 22000:2018', 'ISO 22000:2018 - Sistem menadžmenta bezbednošću hrane'), ('ISO 13485:2016', 'ISO 13485:2016 - Medicinska sredstva - Sistem menadžmenta kvalitetom'), ('ISO 50001:2018', 'ISO 50001:2018 - Sistem menadžmenta energijom'), ('ISO 20000-1:2018', 'ISO 20000-1:2018 - Sistem menadžmenta IT uslugama'), ('ISO 22301:2019', 'ISO 22301:2019 - Sistem menadžmenta kontinuitetom poslovanja'), ('ISO 37001:2016', 'ISO 37001:2016 - Sistem menadžmenta protiv mita'), ('ISO 17025:2017', 'ISO 17025:2017 - Opšti zahtevi za kompetentnost laboratorija za ispitivanje i laboratorija za etaloniranje'), ('ISO 17020:2012', 'ISO 17020:2012 - Ocenjivanje usaglašenosti - Zahtevi za rad različitih tipova tela koja obavljaju kontrolisanje'), ('ISO 17021-1:2015', 'ISO 17021-1:2015 - Ocenjivanje usaglašenosti - Zahtevi za tela koja obavljaju proveru i sertifikaciju sistema menadžmenta'), ('ISO 17024:2012', 'ISO 17024:2012 - Ocenjivanje usaglašenosti - Opšti zahtevi za tela koja obavljaju sertifikaciju osoba'), ('ISO 17065:2012', 'ISO 17065:2012 - Ocenjivanje usaglašenosti - Zahtevi za tela koja sertifikuju proizvode, procese i usluge'), ('HACCP', 'HACCP - Sistem bezbednosti hrane'), ('FSSC 22000 v5.1', 'FSSC 22000 v5.1 - Sistem bezbednosti hrane'), ('IFS Food v7', 'IFS Food v7 - International Featured Standard Food'), ('BRC Food v9', 'BRC Food v9 - British Retail Consortium Global Standard for Food Safety')], max_length=100, null=True, verbose_name='Standard')),
                ('certificate_status', models.CharField(choices=[('active', 'Aktivan'), ('suspended', 'Suspendovan'), ('withdrawn', 'Povučen'), ('expired', 'Istekao'), ('pending', 'Na čekanju'), ('cancelled', 'Otkazan')], default='pending', max_length=50, verbose_name='Status sertifikata')),
                ('suspension_until_date', models.DateField(blank=True, null=True, verbose_name='Suspenzija do datuma')),
                ('audit_days', models.DecimalField(blank=True, decimal_places=1, max_digits=18, null=True, verbose_name='Broj dana audita')),
                ('initial_audit_conducted_date', models.DateField(blank=True, null=True, verbose_name='Datum inicijalnog audita')),
                ('visits_per_year', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Poseta godišnje')),
                ('audit_days_each', models.DecimalField(blank=True, decimal_places=1, max_digits=18, null=True, verbose_name='Dana po auditu')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='company.company', verbose_name='Kompanija')),
            ],
            options={
                'verbose_name': 'Standard',
                'verbose_name_plural': 'Standardi',
                'ordering': ['-init_reg_date'],
            },
        ),
        migrations.CreateModel(
            name='OstalaLokacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Naziv lokacije')),
                ('street', models.CharField(max_length=200, verbose_name='Ulica')),
                ('street_number', models.CharField(max_length=20, verbose_name='Broj')),
                ('city', models.CharField(choices=[('Aleksinac', 'Aleksinac'), ('Aranđelovac', 'Aranđelovac'), ('Bačka Palanka', 'Bačka Palanka'), ('Bačka Topola', 'Bačka Topola'), ('Bajina Bašta', 'Bajina Bašta'), ('Belgrade', 'Belgrade'), ('Bečej', 'Bečej'), ('Bor', 'Bor'), ('Gornji Milanovac', 'Gornji Milanovac'), ('Inđija', 'Inđija'), ('Jagodina', 'Jagodina'), ('Kikinda', 'Kikinda'), ('Kladovo', 'Kladovo'), ('Knjaževac', 'Knjaževac'), ('Kragujevac', 'Kragujevac'), ('Kraljevo', 'Kraljevo'), ('Kruševac', 'Kruševac'), ('Kučevo', 'Kučevo'), ('Leskovac', 'Leskovac'), ('Loznica', 'Loznica'), ('Negotin', 'Negotin'), ('Niš', 'Niš'), ('Nova Varoš', 'Nova Varoš'), ('Novi Pazar', 'Novi Pazar'), ('Novi Sad', 'Novi Sad'), ('Pančevo', 'Pančevo'), ('Paraćin', 'Paraćin'), ('Pirot', 'Pirot'), ('Požarevac', 'Požarevac'), ('Prijepolje', 'Prijepolje'), ('Prokuplje', 'Prokuplje'), ('Ruma', 'Ruma'), ('Smederevo', 'Smederevo'), ('Sombor', 'Sombor'), ('Sremska Mitrovica', 'Sremska Mitrovica'), ('Subotica', 'Subotica'), ('Svilajnac', 'Svilajnac'), ('Šabac', 'Šabac'), ('Užice', 'Užice'), ('Valjevo', 'Valjevo'), ('Velika Plana', 'Velika Plana'), ('Vranje', 'Vranje'), ('Vrnjačka Banja', 'Vrnjačka Banja'), ('Vršac', 'Vršac'), ('Zaječar', 'Zaječar'), ('Zrenjanin', 'Zrenjanin'), ('Čačak', 'Čačak')], help_text='Izaberite grad', max_length=50, verbose_name='Grad')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Poštanski broj')),
                ('country', models.CharField(default='Srbija', max_length=100, verbose_name='Država')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ostale_lokacije', to='company.company', verbose_name='Kompanija')),
            ],
            options={
                'verbose_name': 'Ostala lokacija',
                'verbose_name_plural': 'Ostale lokacije',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
    ]
