# Generated by Django 5.1.6 on 2025-02-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_options_remove_company_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='annual_revenue',
        ),
    ]
