# Generated by Django 5.1.6 on 2025-02-25 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_company_annual_revenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaredneProvere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_surv_due', models.DateField(blank=True, null=True, verbose_name='Prvi nadzor - rok')),
                ('first_surv_cond', models.DateField(blank=True, null=True, verbose_name='Prvi nadzor - izvršen')),
                ('second_surv_due', models.DateField(blank=True, null=True, verbose_name='Drugi nadzor - rok')),
                ('second_surv_cond', models.DateField(blank=True, null=True, verbose_name='Drugi nadzor - izvršen')),
                ('trinial_audit_due', models.DateField(blank=True, null=True, verbose_name='Resertifikacija - rok')),
                ('trinial_audit_cond', models.DateField(blank=True, null=True, verbose_name='Resertifikacija - izvršena')),
                ('status', models.CharField(blank=True, choices=[('scheduled', 'Zakazano'), ('completed', 'Završeno'), ('cancelled', 'Otkazano'), ('pending', 'Na čekanju'), ('overdue', 'Isteklo')], max_length=50, null=True, verbose_name='Status')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naredne_provere', to='company.company', verbose_name='Kompanija')),
            ],
            options={
                'verbose_name': 'Naredna provera',
                'verbose_name_plural': 'Naredne provere',
                'ordering': ['first_surv_due'],
            },
        ),
    ]
