# Generated by Django 5.1.6 on 2025-02-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_naredneprovere'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='naredneprovere',
            options={'verbose_name': 'Naredna provera', 'verbose_name_plural': 'Naredne provere'},
        ),
        migrations.AlterModelOptions(
            name='standard',
            options={'ordering': ['-id'], 'verbose_name': 'Standard', 'verbose_name_plural': 'Standardi'},
        ),
        migrations.RemoveField(
            model_name='standard',
            name='audit_days',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='audit_days_each',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='certificate_no',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='certificate_status',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='init_reg_date',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='initial_audit_conducted_date',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='suspension_until_date',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='visits_per_year',
        ),
        migrations.AddField(
            model_name='company',
            name='audit_days',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=18, null=True, verbose_name='Broj dana audita'),
        ),
        migrations.AddField(
            model_name='company',
            name='audit_days_each',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=18, null=True, verbose_name='Dana po auditu'),
        ),
        migrations.AddField(
            model_name='company',
            name='certificate_status',
            field=models.CharField(choices=[('active', 'Aktivan'), ('suspended', 'Suspendovan'), ('withdrawn', 'Povučen'), ('expired', 'Istekao'), ('pending', 'Na čekanju'), ('cancelled', 'Otkazan')], default='pending', max_length=50, verbose_name='Status sertifikata'),
        ),
        migrations.AddField(
            model_name='company',
            name='initial_audit_conducted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum inicijalnog audita'),
        ),
        migrations.AddField(
            model_name='company',
            name='suspension_until_date',
            field=models.DateField(blank=True, null=True, verbose_name='Suspenzija do datuma'),
        ),
        migrations.AddField(
            model_name='company',
            name='visits_per_year',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Poseta godišnje'),
        ),
        migrations.AlterField(
            model_name='naredneprovere',
            name='first_surv_cond',
            field=models.DateField(blank=True, null=True, verbose_name='Prvi nadzor - održan'),
        ),
        migrations.AlterField(
            model_name='naredneprovere',
            name='first_surv_due',
            field=models.DateField(blank=True, null=True, verbose_name='Prvi nadzor - planiran'),
        ),
        migrations.AlterField(
            model_name='naredneprovere',
            name='second_surv_cond',
            field=models.DateField(blank=True, null=True, verbose_name='Drugi nadzor - održan'),
        ),
        migrations.AlterField(
            model_name='naredneprovere',
            name='second_surv_due',
            field=models.DateField(blank=True, null=True, verbose_name='Drugi nadzor - planiran'),
        ),
        migrations.AlterField(
            model_name='naredneprovere',
            name='status',
            field=models.CharField(choices=[('pending', 'Na čekanju'), ('completed', 'Završeno'), ('delayed', 'Odlagano'), ('overdue', 'Isteklo')], default='pending', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='naredneprovere',
            name='trinial_audit_cond',
            field=models.DateField(blank=True, null=True, verbose_name='Resertifikacija - održana'),
        ),
        migrations.AlterField(
            model_name='naredneprovere',
            name='trinial_audit_due',
            field=models.DateField(blank=True, null=True, verbose_name='Resertifikacija - planirana'),
        ),
    ]
