# Generated by Django 4.2.19 on 2025-02-25 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_naredneprovere_options_alter_standard_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Naslov')),
                ('start', models.DateTimeField(verbose_name='Početak')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Kraj')),
                ('all_day', models.BooleanField(default=False, verbose_name='Celodnevni događaj')),
                ('color', models.CharField(default='#3c8dbc', max_length=20, verbose_name='Boja')),
                ('audit_type', models.CharField(choices=[('first_surv', 'Prvi nadzor'), ('second_surv', 'Drugi nadzor'), ('trinial_audit', 'Resertifikacija')], max_length=50, verbose_name='Tip provere')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Napomene')),
                ('naredne_provere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='company.naredneprovere', verbose_name='Naredne provere')),
            ],
            options={
                'verbose_name': 'Kalendarski događaj',
                'verbose_name_plural': 'Kalendarski događaji',
            },
        ),
    ]
