# Generated by Django 5.1.6 on 2025-02-25 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_calendarevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='audit_type',
            field=models.CharField(blank=True, choices=[('first_surv', 'Prvi nadzor'), ('second_surv', 'Drugi nadzor'), ('trinial_audit', 'Resertifikacija')], max_length=50, null=True, verbose_name='Tip provere'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='naredne_provere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='company.naredneprovere', verbose_name='Naredne provere'),
        ),
    ]
