# Generated by Django 5.1.6 on 2025-02-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_calendarevent_audit_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naredneprovere',
            name='first_surv_cond',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prvi nadzor - održan'),
        ),
        migrations.AlterField(
            model_name='naredneprovere',
            name='first_surv_due',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prvi nadzor - planiran'),
        ),
        migrations.AlterField(
            model_name='naredneprovere',
            name='second_surv_cond',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Drugi nadzor - održan'),
        ),
        migrations.AlterField(
            model_name='naredneprovere',
            name='second_surv_due',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Drugi nadzor - planiran'),
        ),
        migrations.AlterField(
            model_name='naredneprovere',
            name='trinial_audit_cond',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Resertifikacija - održana'),
        ),
        migrations.AlterField(
            model_name='naredneprovere',
            name='trinial_audit_due',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Resertifikacija - planirana'),
        ),
    ]
