# Generated by Django 5.1.6 on 2025-02-26 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_naredneprovere_first_surv_cond_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact_position',
        ),
        migrations.RemoveField(
            model_name='company',
            name='secondary_contact_email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='secondary_contact_person',
        ),
        migrations.RemoveField(
            model_name='company',
            name='secondary_contact_phone',
        ),
        migrations.RemoveField(
            model_name='company',
            name='secondary_contact_position',
        ),
        migrations.CreateModel(
            name='KontaktOsoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_prezime', models.CharField(max_length=200, verbose_name='Ime i prezime')),
                ('pozicija', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pozicija')),
                ('telefon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primarna kontakt osoba')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontakt_osobe', to='company.company', verbose_name='Kompanija')),
            ],
            options={
                'verbose_name': 'Kontakt osoba',
                'verbose_name_plural': 'Kontakt osobe',
                'ordering': ['-is_primary', 'ime_prezime'],
            },
        ),
    ]
