# Generated by Django 5.1.6 on 2025-02-26 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_remove_company_contact_email_and_more'),
    ]

    operations = [
    ]
