# Generated by Django 5.1.6 on 2025-02-26 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_migrate_contact_data'),
    ]

    operations = [
    ]
