# Generated by Django 5.1.6 on 2025-04-11 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_migrate_contact_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Naslov')),
                ('appointment_type', models.CharField(choices=[('audit', 'Audit'), ('meeting', 'Sastanak'), ('consultation', 'Konsultacija'), ('training', 'Trening'), ('other', 'Ostalo')], default='meeting', max_length=50, verbose_name='Tip sastanka')),
                ('start_datetime', models.DateTimeField(verbose_name='Vreme početka')),
                ('end_datetime', models.DateTimeField(verbose_name='Vreme završetka')),
                ('all_day', models.BooleanField(default=False, verbose_name='Celodnevni događaj')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lokacija')),
                ('is_online', models.BooleanField(default=False, verbose_name='Online sastanak')),
                ('meeting_link', models.URLField(blank=True, null=True, verbose_name='Link za sastanak')),
                ('external_attendees', models.TextField(blank=True, help_text='Unesite imena i kontakte eksternih učesnika, jedan po liniji', null=True, verbose_name='Eksterni učesnici')),
                ('status', models.CharField(choices=[('scheduled', 'Zakazano'), ('completed', 'Završeno'), ('cancelled', 'Otkazano'), ('postponed', 'Odloženo')], default='scheduled', max_length=50, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Napomene')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='company.company', verbose_name='Kompanija')),
                ('contact_persons', models.ManyToManyField(blank=True, related_name='appointments', to='company.kontaktosoba', verbose_name='Kontakt osobe')),
            ],
            options={
                'verbose_name': 'Sastanak',
                'verbose_name_plural': 'Sastanci',
                'ordering': ['-start_datetime'],
            },
        ),
    ]
