# Generated by Django 5.1.6 on 2025-04-20 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='IAFEACCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iaf_code', models.CharField(max_length=10, unique=True, verbose_name='IAF/EAC Code')),
                ('description', models.CharField(max_length=255, verbose_name='Code Description')),
                ('sub_descriptors', models.TextField(blank=True, verbose_name='Sub Descriptors (for information only)')),
            ],
            options={
                'verbose_name': 'IAF EAC Code',
                'verbose_name_plural': 'IAF EAC Codes',
                'ordering': ['iaf_code'],
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='certificate_status',
            field=models.CharField(choices=[('active', 'Aktivan'), ('suspended', 'Suspendovan'), ('withdrawn', 'Deregistrovan'), ('expired', 'Istekao'), ('pending', 'Na čekanju'), ('cancelled', 'Otkazan')], default='pending', max_length=50, verbose_name='Status sertifikata'),
        ),
        migrations.CreateModel(
            name='CompanyIAFEACCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary Code')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iaf_eac_links', to='company.company', verbose_name='Company')),
                ('iaf_eac_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_links', to='company.iafeaccode', verbose_name='IAF/EAC Code')),
            ],
            options={
                'verbose_name': 'Company IAF/EAC Code',
                'verbose_name_plural': 'Company IAF/EAC Codes',
                'ordering': ['-is_primary', 'iaf_eac_code__iaf_code'],
                'unique_together': {('company', 'iaf_eac_code')},
            },
        ),
    ]
