# Generated by Django 5.1.6 on 2025-05-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_iafeaccode_alter_company_certificate_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_prezime', models.CharField(max_length=200, verbose_name='Ime i prezime')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefon', models.CharField(max_length=50, verbose_name='Broj telefona')),
                ('kategorija', models.CharField(choices=[('lead_auditor', 'Lead auditor'), ('auditor', 'Auditor'), ('technical_expert', 'Tehnički ekspert'), ('trainer', 'Trainer')], default='auditor', max_length=50, verbose_name='Kategorija')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
            ],
            options={
                'verbose_name': 'Auditor',
                'verbose_name_plural': 'Auditori',
                'ordering': ['ime_prezime'],
            },
        ),
    ]
