# Generated by Django 5.1.6 on 2025-05-07 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_auditor'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod standarda')),
                ('name', models.CharField(max_length=200, verbose_name='Naziv standarda')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis standarda')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
            ],
            options={
                'verbose_name': 'Definicija standarda',
                'verbose_name_plural': 'Definicije standarda',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AuditorStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_potpisivanja', models.DateField(blank=True, null=True, verbose_name='Datum potpisivanja')),
                ('napomena', models.TextField(blank=True, null=True, verbose_name='Napomena')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_standardi', to='company.auditor', verbose_name='Auditor')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_auditori', to='company.standarddefinition', verbose_name='Standard')),
            ],
            options={
                'verbose_name': 'Standard auditora',
                'verbose_name_plural': 'Standardi auditora',
                'ordering': ['-datum_potpisivanja'],
                'unique_together': {('auditor', 'standard')},
            },
        ),
        migrations.AddField(
            model_name='auditor',
            name='standardi',
            field=models.ManyToManyField(related_name='auditori', through='company.AuditorStandard', to='company.standarddefinition', verbose_name='Standardi'),
        ),
    ]
