# Generated by Django 5.1.6 on 2025-05-07 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_standarddefinition_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditor',
            name='standardi',
            field=models.ManyToManyField(related_name='auditori', through='company.AuditorStandard', to='company.standard', verbose_name='Standardi'),
        ),
        migrations.AlterField(
            model_name='auditorstandard',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_auditori', to='company.standard', verbose_name='Standard'),
        ),
    ]
