# Generated by Django 5.1.6 on 2025-05-07 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_alter_auditor_standardi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorStandardIAFEACCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primarni kod')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Napomene')),
                ('auditor_standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iaf_eac_links', to='company.auditorstandard', verbose_name='Standard auditora')),
                ('iaf_eac_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_standard_links', to='company.iafeaccode', verbose_name='IAF/EAC kod')),
            ],
            options={
                'verbose_name': 'IAF/EAC kod standarda auditora',
                'verbose_name_plural': 'IAF/EAC kodovi standarda auditora',
                'ordering': ['-is_primary', 'iaf_eac_code__iaf_code'],
                'unique_together': {('auditor_standard', 'iaf_eac_code')},
            },
        ),
        migrations.AddField(
            model_name='auditorstandard',
            name='iaf_eac_kodovi',
            field=models.ManyToManyField(related_name='auditor_standardi', through='company.AuditorStandardIAFEACCode', to='company.iafeaccode', verbose_name='IAF/EAC kodovi'),
        ),
    ]
