# Generated by Django 5.1.6 on 2025-05-07 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_auditorstandardiafeaccode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubDescriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Naziv')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('iaf_eac_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_descriptors_list', to='company.iafeaccode', verbose_name='IAF/EAC kod')),
            ],
            options={
                'verbose_name': 'Sub Descriptor',
                'verbose_name_plural': 'Sub Descriptors',
                'ordering': ['iaf_eac_code__iaf_code', 'name'],
                'unique_together': {('iaf_eac_code', 'name')},
            },
        ),
    ]
