# Generated by Django 5.1.6 on 2025-05-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_subdescriptor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iafeaccode',
            options={'ordering': ['iaf_scope_reference', 'iaf_code'], 'verbose_name': 'IAF EAC Code', 'verbose_name_plural': 'IAF EAC Codes'},
        ),
        migrations.AddField(
            model_name='iafeaccode',
            name='iaf_scope_reference',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='IAF Scope Reference'),
        ),
        migrations.AlterUniqueTogether(
            name='iafeaccode',
            unique_together={('iaf_scope_reference', 'iaf_code')},
        ),
    ]
