# Generated by Django 5.1.6 on 2025-05-07 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_alter_iafeaccode_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IAFScopeReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=10, unique=True, verbose_name='IAF Scope Reference')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Opis')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
            ],
            options={
                'verbose_name': 'IAF Scope Reference',
                'verbose_name_plural': 'IAF Scope References',
                'ordering': ['reference'],
            },
        ),
        migrations.AlterModelOptions(
            name='iafeaccode',
            options={'ordering': ['iaf_scope_reference__reference', 'iaf_code'], 'verbose_name': 'IAF EAC Code', 'verbose_name_plural': 'IAF EAC Codes'},
        ),
        migrations.AlterUniqueTogether(
            name='iafeaccode',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='iafeaccode',
            name='iaf_scope_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iaf_eac_codes', to='company.iafscopereference', verbose_name='IAF Scope Reference'),
        ),
    ]
