# Generated by Django 5.1.6 on 2025-05-09 00:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_iafscopereference_alter_iafeaccode_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ['start'], 'verbose_name': 'Kalendarski događaj', 'verbose_name_plural': 'Kalendarski događaji'},
        ),
        migrations.AlterModelOptions(
            name='companyiafeaccode',
            options={'ordering': ['-is_primary', 'iaf_eac_code__iaf_code'], 'verbose_name': 'Kompanija IAF/EAC kod', 'verbose_name_plural': 'Kompanija IAF/EAC kodovi'},
        ),
        migrations.AlterModelOptions(
            name='iafeaccode',
            options={'ordering': ['iaf_code'], 'verbose_name': 'IAF/EAC Code', 'verbose_name_plural': 'IAF/EAC Codes'},
        ),
        migrations.AlterModelOptions(
            name='standard',
            options={'ordering': ['-issue_date'], 'verbose_name': 'Standard', 'verbose_name_plural': 'Standardi'},
        ),
        migrations.AlterModelOptions(
            name='subdescriptor',
            options={'ordering': ['id'], 'verbose_name': 'Sub Descriptor', 'verbose_name_plural': 'Sub Descriptors'},
        ),
        migrations.AlterUniqueTogether(
            name='subdescriptor',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='iafeaccode',
            name='sub_descriptors',
        ),
        migrations.RemoveField(
            model_name='iafscopereference',
            name='active',
        ),
        migrations.RemoveField(
            model_name='ostalalokacija',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ostalalokacija',
            name='phone',
        ),
        migrations.AddField(
            model_name='companyiafeaccode',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='companyiafeaccode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AddField(
            model_name='iafeaccode',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='iafeaccode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AddField(
            model_name='kontaktosoba',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='kontaktosoba',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AddField(
            model_name='naredneprovere',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='naredneprovere',
            name='first_surveillance_status',
            field=models.CharField(choices=[('pending', 'Na čekanju'), ('completed', 'Završeno'), ('delayed', 'Odlagano'), ('overdue', 'Isteklo')], default='pending', max_length=50, verbose_name='Status prvog nadzora'),
        ),
        migrations.AddField(
            model_name='naredneprovere',
            name='initial_audit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum inicijalne provere'),
        ),
        migrations.AddField(
            model_name='naredneprovere',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Napomene'),
        ),
        migrations.AddField(
            model_name='naredneprovere',
            name='recertification_status',
            field=models.CharField(choices=[('pending', 'Na čekanju'), ('completed', 'Završeno'), ('delayed', 'Odlagano'), ('overdue', 'Isteklo')], default='pending', max_length=50, verbose_name='Status resertifikacije'),
        ),
        migrations.AddField(
            model_name='naredneprovere',
            name='second_surveillance_status',
            field=models.CharField(choices=[('pending', 'Na čekanju'), ('completed', 'Završeno'), ('delayed', 'Odlagano'), ('overdue', 'Isteklo')], default='pending', max_length=50, verbose_name='Status drugog nadzora'),
        ),
        migrations.AddField(
            model_name='naredneprovere',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AddField(
            model_name='ostalalokacija',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='ostalalokacija',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Napomene'),
        ),
        migrations.AddField(
            model_name='ostalalokacija',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AddField(
            model_name='standard',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='standard',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum isteka'),
        ),
        migrations.AddField(
            model_name='standard',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum izdavanja'),
        ),
        migrations.AddField(
            model_name='standard',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Napomene'),
        ),
        migrations.AddField(
            model_name='standard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('meeting', 'Sastanak'), ('audit', 'Audit'), ('training', 'Trening'), ('consultation', 'Konsultacija'), ('other', 'Ostalo')], default='meeting', max_length=50, verbose_name='Tip sastanka'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kreirano'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vreme završetka'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Zakazan'), ('completed', 'Završen'), ('cancelled', 'Otkazan'), ('postponed', 'Odložen')], default='scheduled', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='auditor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kreirano'),
        ),
        migrations.AlterField(
            model_name='auditor',
            name='standardi',
            field=models.ManyToManyField(related_name='auditori', through='company.AuditorStandard', to='company.standarddefinition', verbose_name='Standardi'),
        ),
        migrations.AlterField(
            model_name='auditorstandard',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kreirano'),
        ),
        migrations.AlterField(
            model_name='auditorstandard',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_auditori', to='company.standarddefinition', verbose_name='Standard'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kreirano'),
        ),
        migrations.AlterField(
            model_name='companyiafeaccode',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iaf_eac_codes', to='company.company', verbose_name='Kompanija'),
        ),
        migrations.AlterField(
            model_name='companyiafeaccode',
            name='iaf_eac_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='company.iafeaccode', verbose_name='IAF/EAC Code'),
        ),
        migrations.AlterField(
            model_name='companyiafeaccode',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Primarni kod'),
        ),
        migrations.AlterField(
            model_name='companyiafeaccode',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Napomene'),
        ),
        migrations.AlterField(
            model_name='iafeaccode',
            name='description',
            field=models.TextField(verbose_name='Code Description'),
        ),
        migrations.AlterField(
            model_name='iafeaccode',
            name='iaf_code',
            field=models.CharField(default='N/A', max_length=10, verbose_name='IAF/EAC Code'),
        ),
        migrations.AlterField(
            model_name='iafscopereference',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kreirano'),
        ),
        migrations.AlterField(
            model_name='iafscopereference',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='naredneprovere',
            name='first_surv_cond',
            field=models.DateField(blank=True, null=True, verbose_name='Prvi nadzor - održano'),
        ),
        migrations.AlterField(
            model_name='naredneprovere',
            name='first_surv_due',
            field=models.DateField(blank=True, null=True, verbose_name='Prvi nadzor - planirano'),
        ),
        migrations.AlterField(
            model_name='naredneprovere',
            name='second_surv_cond',
            field=models.DateField(blank=True, null=True, verbose_name='Drugi nadzor - održano'),
        ),
        migrations.AlterField(
            model_name='naredneprovere',
            name='second_surv_due',
            field=models.DateField(blank=True, null=True, verbose_name='Drugi nadzor - planirano'),
        ),
        migrations.AlterField(
            model_name='naredneprovere',
            name='trinial_audit_cond',
            field=models.DateField(blank=True, null=True, verbose_name='Resertifikacija - održano'),
        ),
        migrations.AlterField(
            model_name='naredneprovere',
            name='trinial_audit_due',
            field=models.DateField(blank=True, null=True, verbose_name='Resertifikacija - planirano'),
        ),
        migrations.AlterField(
            model_name='ostalalokacija',
            name='city',
            field=models.CharField(blank=True, choices=[('Aleksinac', 'Aleksinac'), ('Aranđelovac', 'Aranđelovac'), ('Bačka Palanka', 'Bačka Palanka'), ('Bačka Topola', 'Bačka Topola'), ('Bajina Bašta', 'Bajina Bašta'), ('Belgrade', 'Belgrade'), ('Bečej', 'Bečej'), ('Bor', 'Bor'), ('Gornji Milanovac', 'Gornji Milanovac'), ('Inđija', 'Inđija'), ('Jagodina', 'Jagodina'), ('Kikinda', 'Kikinda'), ('Kladovo', 'Kladovo'), ('Knjaževac', 'Knjaževac'), ('Kragujevac', 'Kragujevac'), ('Kraljevo', 'Kraljevo'), ('Kruševac', 'Kruševac'), ('Kučevo', 'Kučevo'), ('Leskovac', 'Leskovac'), ('Loznica', 'Loznica'), ('Negotin', 'Negotin'), ('Niš', 'Niš'), ('Nova Varoš', 'Nova Varoš'), ('Novi Pazar', 'Novi Pazar'), ('Novi Sad', 'Novi Sad'), ('Pančevo', 'Pančevo'), ('Paraćin', 'Paraćin'), ('Pirot', 'Pirot'), ('Požarevac', 'Požarevac'), ('Prijepolje', 'Prijepolje'), ('Prokuplje', 'Prokuplje'), ('Ruma', 'Ruma'), ('Smederevo', 'Smederevo'), ('Sombor', 'Sombor'), ('Sremska Mitrovica', 'Sremska Mitrovica'), ('Subotica', 'Subotica'), ('Svilajnac', 'Svilajnac'), ('Šabac', 'Šabac'), ('Užice', 'Užice'), ('Valjevo', 'Valjevo'), ('Velika Plana', 'Velika Plana'), ('Vranje', 'Vranje'), ('Vrnjačka Banja', 'Vrnjačka Banja'), ('Vršac', 'Vršac'), ('Zaječar', 'Zaječar'), ('Zrenjanin', 'Zrenjanin'), ('Čačak', 'Čačak')], max_length=50, null=True, verbose_name='Grad'),
        ),
        migrations.AlterField(
            model_name='ostalalokacija',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Poštanski broj'),
        ),
        migrations.AlterField(
            model_name='ostalalokacija',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='ostalalokacija',
            name='street_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Broj'),
        ),
        migrations.AlterField(
            model_name='subdescriptor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kreirano'),
        ),
        migrations.AlterField(
            model_name='subdescriptor',
            name='description',
            field=models.TextField(verbose_name='Sub Descriptor'),
        ),
        migrations.AlterField(
            model_name='subdescriptor',
            name='iaf_eac_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_descriptors', to='company.iafeaccode', verbose_name='IAF/EAC Code'),
        ),
        migrations.AlterUniqueTogether(
            name='standard',
            unique_together={('company', 'standard')},
        ),
        migrations.CreateModel(
            name='StandardIAFScopeReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primarni')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Napomene')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('iaf_scope_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iaf_scope_reference_standards', to='company.iafscopereference', verbose_name='IAF Scope Reference')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_iaf_scope_references', to='company.standarddefinition', verbose_name='Standard')),
            ],
            options={
                'verbose_name': 'Standard IAF Scope Reference',
                'verbose_name_plural': 'Standard IAF Scope References',
                'ordering': ['-is_primary', 'iaf_scope_reference__reference'],
                'unique_together': {('standard', 'iaf_scope_reference')},
            },
        ),
        migrations.AddField(
            model_name='standarddefinition',
            name='iaf_scope_references',
            field=models.ManyToManyField(related_name='standards', through='company.StandardIAFScopeReference', to='company.iafscopereference', verbose_name='IAF Scope References'),
        ),
        migrations.RemoveField(
            model_name='subdescriptor',
            name='active',
        ),
        migrations.RemoveField(
            model_name='subdescriptor',
            name='name',
        ),
    ]
