# Generated by Django 5.1.6 on 2025-05-09 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_alter_standarddefinition_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companystandard',
            name='standard',
            field=models.CharField(blank=True, choices=[('ISO 9001:2015', 'ISO 9001:2015 - Sistem menadžmenta kvalitetom'), ('ISO 14001:2015', 'ISO 14001:2015 - Sistem upravljanja zaštitom životne sredine'), ('ISO 45001:2018', 'ISO 45001:2018 - Sistem menadžmenta bezbednošću i zdravljem na radu'), ('ISO 27001:2022', 'ISO 27001:2022 - Sistem menadžmenta bezbednošću informacija'), ('ISO 22000:2018', 'ISO 22000:2018 - Sistem menadžmenta bezbednošću hrane'), ('ISO 13485:2016', 'ISO 13485:2016 - Medicinska sredstva - Sistem menadžmenta kvalitetom'), ('ISO 50001:2018', 'ISO 50001:2018 - Sistem menadžmenta energijom'), ('ISO 20000-1:2018', 'ISO 20000-1:2018 - Sistem menadžmenta IT uslugama'), ('ISO 22301:2019', 'ISO 22301:2019 - Sistem menadžmenta kontinuitetom poslovanja'), ('ISO 37001:2016', 'ISO 37001:2016 - Sistem menadžmenta protiv mita'), ('ISO 17025:2017', 'ISO 17025:2017 - Opšti zahtevi za kompetentnost laboratorija za ispitivanje i laboratorija za etaloniranje'), ('ISO 17020:2012', 'ISO 17020:2012 - Ocenjivanje usaglašenosti - Zahtevi za rad različitih tipova tela koja obavljaju kontrolisanje'), ('ISO 17021-1:2015', 'ISO 17021-1:2015 - Ocenjivanje usaglašenosti - Zahtevi za tela koja obavljaju proveru i sertifikaciju sistema menadžmenta'), ('ISO 17024:2012', 'ISO 17024:2012 - Ocenjivanje usaglašenosti - Opšti zahtevi za tela koja obavljaju sertifikaciju osoba'), ('ISO 17065:2012', 'ISO 17065:2012 - Ocenjivanje usaglašenosti - Zahtevi za tela koja sertifikuju proizvode, procese i usluge'), ('HACCP', 'HACCP - Sistem bezbednosti hrane'), ('FSSC 22000 v5.1', 'FSSC 22000 v5.1 - Sistem bezbednosti hrane'), ('IFS Food v7', 'IFS Food v7 - International Featured Standard Food'), ('BRC Food v9', 'BRC Food v9 - British Retail Consortium Global Standard for Food Safety')], help_text='Staro polje za standard, koristite standard_definition umesto ovog polja', max_length=100, null=True, verbose_name='Standard (staro)'),
        ),
        migrations.AlterField(
            model_name='companystandard',
            name='standard_definition',
            field=models.ForeignKey(help_text='Izaberite standard iz liste definisanih standarda', on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='company.standarddefinition', verbose_name='Standard'),
        ),
    ]
