# Generated by Django 5.1.6 on 2025-05-10 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_alter_companystandard_standard_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubDescriptor',
        ),
    ]
