# Generated by Django 5.1.6 on 2025-05-11 00:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_remove_subdescriptor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_integrated_system', models.BooleanField(default=False, help_text='Označiti ako je u pitanju integrisani sistem koji obuhvata ISO 9001, 14001 i/ili 45001 standard', verbose_name='Integrisani sistem menadžmenta')),
                ('start_date', models.DateField(help_text='Datum inicijalne sertifikacije', verbose_name='Datum početka ciklusa')),
                ('end_date', models.DateField(help_text='Datum isteka ciklusa (3 godine nakon inicijalne sertifikacije)', verbose_name='Datum završetka ciklusa')),
                ('status', models.CharField(choices=[('active', 'Aktivan'), ('completed', 'Završen'), ('cancelled', 'Otkazan')], default='active', max_length=20, verbose_name='Status ciklusa')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Napomene')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_cycles', to='company.company', verbose_name='Kompanija')),
            ],
            options={
                'verbose_name': 'Ciklus sertifikacije',
                'verbose_name_plural': 'Ciklusi sertifikacije',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CycleAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_type', models.CharField(choices=[('initial', 'Inicijalni audit'), ('surveillance_1', 'Prvi nadzorni audit'), ('surveillance_2', 'Drugi nadzorni audit'), ('recertification', 'Resertifikacija'), ('special', 'Specijalni audit')], max_length=20, verbose_name='Tip audita')),
                ('audit_status', models.CharField(choices=[('planned', 'Planirano'), ('in_progress', 'U toku'), ('completed', 'Završeno'), ('cancelled', 'Otkazano')], default='planned', max_length=20, verbose_name='Status audita')),
                ('planned_date', models.DateField(verbose_name='Planirani datum')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='Stvarni datum')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Datum završetka')),
                ('report_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Broj izveštaja')),
                ('findings', models.TextField(blank=True, null=True, verbose_name='Nalazi')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Preporuke')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Napomene')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('audit_team', models.ManyToManyField(blank=True, related_name='audit_participations', to='company.auditor', verbose_name='Tim auditora')),
                ('certification_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='company.certificationcycle', verbose_name='Ciklus sertifikacije')),
                ('lead_auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_audits', to='company.auditor', verbose_name='Vodeći auditor')),
            ],
            options={
                'verbose_name': 'Audit u ciklusu',
                'verbose_name_plural': 'Auditi u ciklusu',
                'ordering': ['planned_date'],
            },
        ),
        migrations.CreateModel(
            name='CycleStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Napomene')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('certification_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_standards', to='company.certificationcycle', verbose_name='Ciklus sertifikacije')),
                ('company_standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certification_cycles', to='company.companystandard', verbose_name='Standard kompanije')),
                ('standard_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_cycles', to='company.standarddefinition', verbose_name='Standard')),
            ],
            options={
                'verbose_name': 'Standard u ciklusu',
                'verbose_name_plural': 'Standardi u ciklusu',
                'unique_together': {('certification_cycle', 'standard_definition')},
            },
        ),
    ]
