# Generated by Django 5.1.6 on 2025-05-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_certificationcycle_cycleaudit_cyclestandard'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='oblast_registracije',
            field=models.TextField(blank=True, help_text='Unesite oblast registracije kompanije', null=True, verbose_name='Oblast registracije'),
        ),
    ]
