# Generated by Django 5.1.6 on 2025-05-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_company_oblast_registracije'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Broj sertifikata'),
        ),
    ]
