# Generated by Django 5.1.6 on 2025-06-02 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_company_certificate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='naredneprovere',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='company.auditor', verbose_name='Auditor'),
        ),
    ]
