# Generated by Django 5.1.6 on 2025-06-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_naredneprovere_auditor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationcycle',
            name='end_date',
            field=models.DateField(blank=True, help_text='Datum isteka ciklusa (3 godine nakon inicijalne sertifikacije)', null=True, verbose_name='Datum završetka ciklusa'),
        ),
    ]
