# Generated by Django 5.1.6 on 2025-06-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0032_remove_naredne_provere'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationcycle',
            name='broj_dana_nadzora',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Broj dana za nadzorni audit', max_digits=5, null=True, verbose_name='Broj dana nadzora'),
        ),
        migrations.AddField(
            model_name='certificationcycle',
            name='broj_dana_resertifikacije',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Broj dana za resertifikacioni audit', max_digits=5, null=True, verbose_name='Broj dana resertifikacije'),
        ),
        migrations.AddField(
            model_name='certificationcycle',
            name='inicijalni_broj_dana',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Broj dana za inicijalni audit', max_digits=5, null=True, verbose_name='Inicijalni broj dana'),
        ),
    ]
