# Generated by Django 5.1.6 on 2025-06-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_certificationcycle_broj_dana_nadzora_and_more'),
        ('company', '0034_rename_start_date_and_remove_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificationcycle',
            name='broj_dana_nadzora',
        ),
        migrations.RemoveField(
            model_name='certificationcycle',
            name='broj_dana_resertifikacije',
        ),
        migrations.RemoveField(
            model_name='certificationcycle',
            name='inicijalni_broj_dana',
        ),
        migrations.AddField(
            model_name='cycleaudit',
            name='broj_dana_nadzora',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Broj dana za nadzorni audit', max_digits=5, null=True, verbose_name='Broj dana nadzora'),
        ),
        migrations.AddField(
            model_name='cycleaudit',
            name='broj_dana_resertifikacije',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Broj dana za resertifikacioni audit', max_digits=5, null=True, verbose_name='Broj dana resertifikacije'),
        ),
        migrations.AddField(
            model_name='cycleaudit',
            name='datum_sprovodjenja_inicijalne',
            field=models.DateField(blank=True, help_text='Datum kada je sprovedena inicijalna provera', null=True, verbose_name='Datum sprovođenja inicijalne'),
        ),
        migrations.AddField(
            model_name='cycleaudit',
            name='inicijalni_broj_dana',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Broj dana za inicijalni audit', max_digits=5, null=True, verbose_name='Inicijalni broj dana'),
        ),
    ]
