# Generated by Django 5.1.6 on 2025-06-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0035_remove_certificationcycle_broj_dana_nadzora_and_more'),
    ]

    operations = [
    ]
