# Generated by Django 5.1.6 on 2025-06-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0036_move_dana_fields_to_cycle_audit'),
    ]

    operations = [
    ]
