# Generated by Django 5.1.6 on 2025-06-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0037_move_dana_fields_to_cycle_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationcycle',
            name='broj_dana_nadzora',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Planirani broj dana za nadzorni audit', max_digits=5, null=True, verbose_name='Planirani dani nadzora'),
        ),
        migrations.AddField(
            model_name='certificationcycle',
            name='broj_dana_resertifikacije',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Planirani broj dana za resertifikacioni audit', max_digits=5, null=True, verbose_name='Planirani dani resertifikacije'),
        ),
        migrations.AddField(
            model_name='certificationcycle',
            name='inicijalni_broj_dana',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Planirani broj dana za inicijalni audit', max_digits=5, null=True, verbose_name='Planirani inicijalni dani'),
        ),
    ]
