# Generated by Django 5.1.6 on 2025-06-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0038_certificationcycle_broj_dana_nadzora_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycleaudit',
            name='broj_dana_nadzora',
        ),
        migrations.RemoveField(
            model_name='cycleaudit',
            name='broj_dana_resertifikacije',
        ),
        migrations.RemoveField(
            model_name='cycleaudit',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='cycleaudit',
            name='datum_sprovodjenja_inicijalne',
        ),
        migrations.RemoveField(
            model_name='cycleaudit',
            name='inicijalni_broj_dana',
        ),
    ]
