# Generated by Django 5.1.6 on 2025-06-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0039_remove_audit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationcycle',
            name='datum_sprovodjenja_inicijalne',
            field=models.DateField(blank=True, help_text='Datum kada je sprovedena inicijalna provera', null=True, verbose_name='Datum sprovođenja inicijalne'),
        ),
    ]
