# Generated by Django 5.1.6 on 2025-07-02 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0040_certificationcycle_datum_sprovodjenja_inicijalne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycleaudit',
            name='audit_status',
            field=models.CharField(choices=[('planned', 'Planirano'), ('in_progress', 'U toku'), ('completed', 'Završeno'), ('cancelled', 'Otkazano'), ('postponed', 'Odloženo')], default='planned', max_length=20, verbose_name='Status audita'),
        ),
        migrations.AlterField(
            model_name='cycleaudit',
            name='audit_type',
            field=models.CharField(choices=[('initial', 'Inicijalni'), ('surveillance_1', 'Prvi nadzor'), ('surveillance_2', 'Drugi nadzor'), ('recertification', 'Resertifikacija'), ('special', 'Specijalni')], max_length=20, verbose_name='Tip audita'),
        ),
        migrations.CreateModel(
            name='AuditDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('is_planned', models.BooleanField(default=True, verbose_name='Planirano')),
                ('is_actual', models.BooleanField(default=False, verbose_name='Stvarno')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Napomene')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_days', to='company.cycleaudit', verbose_name='Audit')),
            ],
            options={
                'verbose_name': 'Dan audita',
                'verbose_name_plural': 'Dani audita',
                'ordering': ['date'],
            },
        ),
    ]
