# Generated by Django 5.1.6 on 2025-07-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0041_alter_cycleaudit_audit_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycleaudit',
            name='poslat_izvestaj',
            field=models.BooleanField(default=False, help_text='Označite ako je izveštaj poslat klijentu', verbose_name='Poslat izveštaj'),
        ),
    ]
