# Generated by Django 5.1.6 on 2025-08-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0042_cycleaudit_poslat_izvestaj'),
        ('company', '0043_rename_start_date_to_planirani_datum_and_remove_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificationcycle',
            options={'ordering': ['-planirani_datum'], 'verbose_name': 'Ciklus sertifikacije', 'verbose_name_plural': 'Ciklusi sertifikacije'},
        ),
    ]
