# Generated by Django 5.1.6 on 2025-08-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0034_rename_start_date_and_remove_end_date'),
        ('company', '0043_rename_start_date_to_planirani_datum_and_remove_end_date'),
        ('company', '0044a_alter_certificationcycle_options_and_more'),
    ]

    operations = [
    ]
