# Generated by Django 5.1.6 on 2025-08-22 12:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0044_merge_20250814_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationcycle',
            name='planirani_datum',
            field=models.DateField(help_text='Datum inicijalne sertifikacije', verbose_name='Planirani datum ciklusa'),
        ),
        migrations.CreateModel(
            name='AuditorReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('role', models.CharField(blank=True, choices=[('lead', 'Vodeći'), ('team', 'Tim')], max_length=10, null=True, verbose_name='Uloga')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_reservations', to='company.cycleaudit', verbose_name='Audit')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='company.auditor', verbose_name='Auditor')),
            ],
            options={
                'verbose_name': 'Rezervacija auditora',
                'verbose_name_plural': 'Rezervacije auditora',
                'ordering': ['date'],
                'unique_together': {('auditor', 'date')},
            },
        ),
    ]
