# Generated by Django 5.1.6 on 2025-08-26 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0046_alter_certificationcycle_planirani_datum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorreservation',
            name='audit_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='company.auditday', verbose_name='Dan audita'),
        ),
    ]
