# Generated by Django 5.1.6 on 2025-09-15 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0048_backfill_auditorreservation_auditday'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorIAFEACCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primarni kod')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Napomene')),
            ],
            options={
                'verbose_name': 'IAF/EAC kod auditora (TE)',
                'verbose_name_plural': 'IAF/EAC kodovi auditora (TE)',
                'ordering': ['-is_primary', 'iaf_eac_code__iaf_code'],
            },
        ),
        migrations.AddIndex(
            model_name='auditorreservation',
            index=models.Index(fields=['audit', 'date'], name='audres_audit_date_idx'),
        ),
        migrations.AddField(
            model_name='auditoriafeaccode',
            name='auditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_iaf_links', to='company.auditor', verbose_name='Auditor'),
        ),
        migrations.AddField(
            model_name='auditoriafeaccode',
            name='iaf_eac_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_direct_links', to='company.iafeaccode', verbose_name='IAF/EAC kod'),
        ),
        migrations.AddField(
            model_name='auditor',
            name='iaf_eac_codes',
            field=models.ManyToManyField(blank=True, related_name='auditori_direktni', through='company.AuditorIAFEACCode', to='company.iafeaccode', verbose_name='IAF/EAC kodovi (TE)'),
        ),
        migrations.AlterUniqueTogether(
            name='auditoriafeaccode',
            unique_together={('auditor', 'iaf_eac_code')},
        ),
    ]
