# Generated by Django 5.1.12 on 2025-09-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0049_auditoriafeaccode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(choices=[('AD', 'Andora'), ('AL', 'Albanija'), ('AT', 'Austrija'), ('BA', 'Bosna i Hercegovina'), ('BE', 'Belgija'), ('BG', 'Bugarska'), ('BY', 'Belorusija'), ('CH', 'Švajcarska'), ('CY', 'Kipar'), ('CZ', 'Češka'), ('DE', 'Nemačka'), ('DK', 'Danska'), ('EE', 'Estonija'), ('ES', 'Španija'), ('FI', 'Finska'), ('FR', 'Francuska'), ('GB', 'Velika Britanija'), ('GR', 'Grčka'), ('HR', 'Hrvatska'), ('HU', 'Mađarska'), ('IE', 'Irska'), ('IS', 'Island'), ('IT', 'Italija'), ('LI', 'Lihtenštajn'), ('LT', 'Litvanija'), ('LU', 'Luksemburg'), ('LV', 'Letonija'), ('MC', 'Monako'), ('MD', 'Moldavija'), ('ME', 'Crna Gora'), ('MK', 'Severna Makedonija'), ('MT', 'Malta'), ('NL', 'Holandija'), ('NO', 'Norveška'), ('PL', 'Poljska'), ('PT', 'Portugal'), ('RO', 'Rumunija'), ('RS', 'Srbija'), ('RU', 'Rusija'), ('SE', 'Švedska'), ('SI', 'Slovenija'), ('SK', 'Slovačka'), ('SM', 'San Marino'), ('TR', 'Turska'), ('UA', 'Ukrajina'), ('VA', 'Vatikan'), ('XK', 'Kosovo')], default='RS', help_text='Izaberite državu', max_length=2, verbose_name='Država'),
        ),
    ]
