# Generated by Django 5.1.12 on 2025-09-29 19:58

import company.company_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0052_update_location_country_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='mb',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[company.company_models.validate_mb_optional], verbose_name='Matični broj'),
        ),
        migrations.AlterField(
            model_name='company',
            name='pib',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[company.company_models.validate_pib_optional], verbose_name='PIB'),
        ),
    ]
