# Generated by Django 5.1.12 on 2025-10-02 22:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0052_update_pib_mb_validators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycleaudit',
            name='audit_status',
            field=models.CharField(choices=[('planned', 'Planirano'), ('postponed', 'Odloženo'), ('scheduled', 'Zakazano'), ('completed', 'Završeno'), ('cancelled', 'Otkazano')], default='planned', max_length=20, verbose_name='Status audita'),
        ),
        migrations.CreateModel(
            name='SrbijaTim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(help_text='Broj sertifikata kompanije', max_length=100, verbose_name='Broj sertifikata')),
                ('company_name', models.CharField(help_text='Naziv kompanije', max_length=255, verbose_name='Naziv firme')),
                ('certificate_expiry_date', models.DateField(blank=True, help_text='Datum kada ističe sertifikat', null=True, verbose_name='Datum isticanja sertifikata')),
                ('visit_date', models.DateField(help_text='Datum kada je održan sastanak/poseta', verbose_name='Datum održanog sastanka')),
                ('report_sent', models.BooleanField(default=False, help_text='Da li je izveštaj poslat', verbose_name='Poslat izveštaj')),
                ('notes', models.TextField(blank=True, help_text='Dodatne napomene o poseti', null=True, verbose_name='Napomene')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('auditors', models.ManyToManyField(help_text='Auditori koji su učestvovali u poseti', related_name='srbija_tim_visits', to='company.auditor', verbose_name='Auditori')),
                ('company', models.ForeignKey(blank=True, help_text='Povezana kompanija iz baze (opciono)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='srbija_tim_visits', to='company.company', verbose_name='Kompanija')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_srbija_tim_visits', to=settings.AUTH_USER_MODEL, verbose_name='Kreirao')),
                ('standards', models.ManyToManyField(help_text='Standardi za koje se vrši audit', related_name='srbija_tim_visits', to='company.standarddefinition', verbose_name='Standardi')),
            ],
            options={
                'verbose_name': 'Srbija Tim - Poseta',
                'verbose_name_plural': 'Srbija Tim - Posete',
                'ordering': ['-visit_date', '-created_at'],
                'indexes': [models.Index(fields=['-visit_date'], name='company_srb_visit_d_f9d769_idx'), models.Index(fields=['certificate_number'], name='company_srb_certifi_2f9ab1_idx'), models.Index(fields=['report_sent'], name='company_srb_report__1f3736_idx')],
            },
        ),
    ]
