# Generated by Django 5.1.12 on 2025-10-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0053_alter_cycleaudit_audit_status_srbijatim'),
    ]

    operations = [
        migrations.AddField(
            model_name='srbijatim',
            name='visit_time',
            field=models.TimeField(blank=True, help_text='Vreme kada je održan sastanak/poseta (opciono)', null=True, verbose_name='Vreme održanog sastanka'),
        ),
    ]
