# Generated by Django 5.1.12 on 2025-10-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0054_add_visit_time_to_srbija_tim'),
    ]

    operations = [
        migrations.AddField(
            model_name='srbijatim',
            name='auditor_name',
            field=models.CharField(blank=True, help_text='Ime auditora (tekstualno polje)', max_length=255, null=True, verbose_name='Ime auditora'),
        ),
        migrations.AlterField(
            model_name='srbijatim',
            name='auditors',
            field=models.ManyToManyField(blank=True, help_text='Auditori koji su učestvovali u poseti', related_name='srbija_tim_visits', to='company.auditor', verbose_name='Auditori'),
        ),
    ]
