# Generated by Django 5.1.12 on 2025-10-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0056_add_auditor_name_to_srbija_tim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srbijatim',
            name='auditor_name',
        ),
        migrations.AlterField(
            model_name='srbijatim',
            name='auditors',
            field=models.ManyToManyField(help_text='Auditori koji su učestvovali u poseti', related_name='srbija_tim_visits', to='company.auditor', verbose_name='Auditori'),
        ),
    ]
