# Generated by Django 5.1.12 on 2025-10-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0057_remove_company_name_from_srbija_tim'),
    ]

    operations = [
        migrations.AddField(
            model_name='srbijatim',
            name='status',
            field=models.CharField(choices=[('zakazan', 'Zakazan'), ('nije_zakazan', 'Nije zakazan'), ('odradjena', 'Odrađena poseta')], default='nije_zakazan', help_text='Status posete', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='srbijatim',
            name='visit_date',
            field=models.DateField(help_text='Datum kada je planiran sastanak/poseta', verbose_name='Datum planiranog sastanka'),
        ),
        migrations.AlterField(
            model_name='srbijatim',
            name='visit_time',
            field=models.TimeField(blank=True, help_text='Vreme kada je planiran sastanak/poseta (opciono)', null=True, verbose_name='Vreme planiranog sastanka'),
        ),
    ]
