# Generated by Django 5.1.10 on 2025-10-06 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0057_remove_auditor_name_from_srbija_tim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srbijatim',
            name='company_name',
        ),
        migrations.AlterField(
            model_name='srbijatim',
            name='company',
            field=models.ForeignKey(help_text='Kompanija iz baze', on_delete=django.db.models.deletion.CASCADE, related_name='srbija_tim_visits', to='company.company', verbose_name='Kompanija'),
        ),
    ]
