# Generated by Django 5.1.10 on 2025-11-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0059_add_status_to_srbija_tim'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditor',
            name='covers_all_standards',
            field=models.BooleanField(default=False, help_text='Označite ako auditor pokriva sve dostupne standarde', verbose_name='Pokriva sve standarde'),
        ),
        migrations.AddField(
            model_name='auditor',
            name='technical_area_code',
            field=models.CharField(blank=True, help_text='Technical Area kod (npr. T09)', max_length=10, null=True, verbose_name='TA kod'),
        ),
    ]
