# Generated by Django 5.2.7 on 2025-11-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0060_add_auditor_import_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iafeaccode',
            name='iaf_code',
            field=models.CharField(default='N/A', max_length=20, verbose_name='IAF/EAC Code'),
        ),
    ]
