# Generated by Django 5.1.10 on 2025-11-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0060_extend_iaf_code_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iafeaccode',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Code Description'),
        ),
        migrations.AlterField(
            model_name='iafeaccode',
            name='iaf_code',
            field=models.CharField(default='N/A', max_length=50, verbose_name='IAF/EAC Code'),
        ),
        migrations.AlterField(
            model_name='iafscopereference',
            name='reference',
            field=models.CharField(max_length=50, unique=True, verbose_name='IAF Scope Reference'),
        ),
    ]
