# Generated by Django 5.2.8 on 2025-11-21 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0064_remove_audit_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srbijatim',
            name='auditors',
            field=models.ManyToManyField(blank=True, help_text='Auditori koji su učestvovali u poseti', related_name='srbija_tim_visits', to='company.auditor', verbose_name='Auditori'),
        ),
        migrations.AlterField(
            model_name='srbijatim',
            name='certificate_number',
            field=models.CharField(blank=True, help_text='Broj sertifikata kompanije', max_length=100, null=True, verbose_name='Broj sertifikata'),
        ),
        migrations.AlterField(
            model_name='srbijatim',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Kompanija iz baze', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='srbija_tim_visits', to='company.company', verbose_name='Kompanija'),
        ),
        migrations.AlterField(
            model_name='srbijatim',
            name='standards',
            field=models.ManyToManyField(blank=True, help_text='Standardi za koje se vrši audit', related_name='srbija_tim_visits', to='company.standarddefinition', verbose_name='Standardi'),
        ),
        migrations.AlterField(
            model_name='srbijatim',
            name='visit_date',
            field=models.DateField(blank=True, help_text='Datum kada je planiran sastanak/poseta', null=True, verbose_name='Datum planiranog sastanka'),
        ),
    ]
