# Generated by Django 5.2.8 on 2025-11-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0065_make_srbija_tim_fields_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='srbijatim',
            name='broj_dana_posete',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Broj dana trajanja posete', max_digits=5, null=True, verbose_name='Broj dana posete'),
        ),
    ]
