# Generated by Django 5.2.8 on 2025-11-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0066_add_broj_dana_posete_to_srbija_tim'),
    ]

    operations = [
        migrations.AddField(
            model_name='srbijatim',
            name='group_id',
            field=models.CharField(blank=True, help_text='UUID za grupisanje povezanih poseta', max_length=100, null=True, verbose_name='ID grupe'),
        ),
    ]
