# Generated by Django 5.2.8 on 2025-11-22 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0067_add_group_id_to_srbija_tim'),
    ]

    operations = [
        migrations.CreateModel(
            name='SrbijaTimDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, help_text='Datum ovog dana posete', null=True, verbose_name='Datum dana posete')),
                ('visit_time', models.TimeField(blank=True, help_text='Vreme kada počinje poseta ovog dana', null=True, verbose_name='Vreme posete')),
                ('day_number', models.PositiveIntegerField(default=1, help_text='Redni broj dana u višednevnoj poseti (1, 2, 3...)', verbose_name='Redni broj dana')),
                ('notes', models.TextField(blank=True, help_text='Specifične napomene za ovaj dan posete', null=True, verbose_name='Napomene za ovaj dan')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_days', to='company.srbijatim', verbose_name='Poseta')),
            ],
            options={
                'verbose_name': 'Dan posete',
                'verbose_name_plural': 'Dani posete',
                'ordering': ['date', 'day_number'],
                'unique_together': {('visit', 'day_number')},
            },
        ),
    ]
