# Generated by Django 5.2.8 on 2025-11-29 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0068_add_srbija_tim_day_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(help_text='Jedinstveni broj sertifikata', max_length=100, unique=True, verbose_name='Broj sertifikata')),
                ('status', models.CharField(choices=[('active', 'Aktivan'), ('suspended', 'Suspendovan'), ('withdrawn', 'Deregistrovan'), ('expired', 'Istekao'), ('pending', 'Na čekanju'), ('cancelled', 'Otkazan')], default='pending', max_length=50, verbose_name='Status')),
                ('suspension_until_date', models.DateField(blank=True, null=True, verbose_name='Suspenzija do datuma')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Datum izdavanja')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Datum isteka')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Napomene')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='company.company', verbose_name='Kompanija')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikati',
                'ordering': ['-created_at'],
            },
        ),
    ]
