# Generated by Django 5.2.8 on 2026-01-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0069_add_certificate_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystandard',
            name='certificate_number',
            field=models.CharField(blank=True, help_text='Broj sertifikata za ovaj standard', max_length=100, null=True, verbose_name='Broj sertifikata'),
        ),
    ]
