# Generated by Django 5.2.8 on 2026-01-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0070_companystandard_certificate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, help_text='Unesite grad', max_length=100, null=True, verbose_name='Grad'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(default='Srbija', help_text='Unesite državu', max_length=100, verbose_name='Država'),
        ),
        migrations.AlterField(
            model_name='ostalalokacija',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Grad'),
        ),
        migrations.AlterField(
            model_name='ostalalokacija',
            name='country',
            field=models.CharField(default='Srbija', help_text='Unesite državu', max_length=100, verbose_name='Država'),
        ),
    ]
