# Generated by Django 5.2.8 on 2026-01-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0071_change_city_country_to_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystandard',
            name='certificate_status',
            field=models.CharField(choices=[('active', 'Aktivan'), ('suspended', 'Suspendovan'), ('withdrawn', 'Povučen'), ('expired', 'Istekao'), ('pending', 'U procesu')], default='pending', help_text='Status sertifikata za ovaj standard', max_length=20, verbose_name='Status sertifikata'),
        ),
    ]
